name: PHPCS check

on: [push, pull_request]

jobs:
  phpcs:
      name: PHP Code Standards
      runs-on: ubuntu-latest
      steps:
        - name: Install dependencies
          run: composer install --dev --prefer-dist --no-progress --no-suggest
        - name: PHPCS check
          uses: chekalsky/phpcs-action@v1
          with:
            phpcs_bin_path: './vendor/bin/phpcs'
            enable_warnings: true
